### ISSUE TITLE
Issue compiling FastPCA with gcc > 7

### ISSUE THREAD

**Issue by MamtaMohan** [moldyn/FastPCA#1]
Hi,

I am trying to compile FastPCA and am running into the following error:

```
  9%] Building CXX object src/CMakeFiles/covariance.dir/covariance.cpp.o
/home/mamta/Software/FastPCA-master/src/covariance.cpp: In function ‘FastPCA::{anonymous}::_CovAccumulation FastPCA::{anonymous}::_accumulate_covariance(const FastPCA::Matrix<double>&)’:
/home/mamta/Software/FastPCA-master/src/covariance.cpp:80:11: error: ‘nr’ not specified in enclosing ‘parallel’
   80 |           for (t = 0; t < nr; ++t) {
      |           ^~~
/home/mamta/Software/FastPCA-master/src/covariance.cpp:75:19: error: enclosing ‘parallel’
   75 |           #pragma omp parallel for default(none)\
      |                   ^~~
make[2]: *** [src/CMakeFiles/covariance.dir/build.make:63: src/CMakeFiles/covariance.dir/covariance.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:144: src/CMakeFiles/covariance.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
I am using:
- Ubuntu 20.04
- cmake version 3.16
- g++ 9.3.0
- libboost 1.71
- LAPACK 3.9.0
- OpenMP 1:10-50~exp1

I followed the install steps in the README and everything worked except for the final `make` command.

**Comment by MamtaMohan** [comment]
Hi,

I was wondering if you can help me out with the issue I posted earlier.

FastPCA does not compile with Ubuntu 20.04 lts.

Mamta

**Comment by simonbray** [comment]
Hi @MamtaMohan,

Unfortunately I can't help you with the compilation, but if you are a conda user you can also install without compilation with `conda install fastpca -c conda-forge`. Perhaps this is useful to you.

ping @moldyn-nagel

**Comment by moldyn-nagel** [comment]
Hi @MamtaMohan,
Did you try to use the gcc8 branch?
```
git clone --branch fix_gcc8 https://github.com/moldyn/FastPCA.git
cd FastPCA && mkdir build && cd build
cmake ..
make
```
Please let me know if it keeps failing.
Best

**Comment by moldyn-nagel** [comment]
> Hi @MamtaMohan,
> 
> Unfortunately I can't help you with the compilation, but if you are a conda user you can also install without compilation with `conda install fastpca -c conda-forge`. Perhaps this is useful to you.
> 
> ping @moldyn-nagel

I've added conda to the README.

**Comment by MamtaMohan** [comment]
I tried conda. It worked. I have not tested yet. If I have an issue I will write again.

Thank you for your help.

Mamta
